// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NanolekPrototype.Context;

namespace NanolekPrototype.Context.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210902063352_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.PackagingProtocol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InternalCodeGP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PackageNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackagingProtocolStatus")
                        .HasColumnType("int");

                    b.Property<string>("ResponsibleUserOOKId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResponsibleUserTLFId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SellBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ShelfLife")
                        .HasColumnType("float");

                    b.Property<string>("SpecificationGP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleUserOOKId");

                    b.HasIndex("ResponsibleUserTLFId");

                    b.ToTable("PackagingProtocols");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.PackagingProtocolForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PackagingProtocolId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackagingProtocolId");

                    b.ToTable("PackagingProtocolForms");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PackagingProtocolForm");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableCheckingProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ActualWeightOfGPPack")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FormCheckingCheckweighingSettingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ReferenceWeightOfGPPack")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExecutorId");

                    b.HasIndex("FormCheckingCheckweighingSettingId");

                    b.ToTable("CheckingProcedures");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableMovementOfBulkProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExecutorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FormReceptionAndMovementOfBulkProductId")
                        .HasColumnType("int");

                    b.Property<int>("GarbageKg")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExecutorId");

                    b.HasIndex("FormReceptionAndMovementOfBulkProductId");

                    b.ToTable("MovementOfBulkProducts");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TablePackagingControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActualTemperatureOfBlisterAdhesion")
                        .HasColumnType("int");

                    b.Property<int>("ActualTemperatureOfCellFormingMax")
                        .HasColumnType("int");

                    b.Property<int>("ActualTemperatureOfCellFormingMin")
                        .HasColumnType("int");

                    b.Property<int>("BlisteringSpeed")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormControlOfPrimaryPackagingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAppereanceWithoutDefects")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBulkProductWithoutVisibleDamage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClarityMarkAndCorrugationPattern")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrespondsCountOfTabletsInBlister")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFoilCorrespondenceToSpecification")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMatchingVariableData")
                        .HasColumnType("bit");

                    b.Property<string>("TaskMasterId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FormControlOfPrimaryPackagingId");

                    b.HasIndex("TaskMasterId");

                    b.ToTable("PackagingControls");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TablePersonnelAccessProtocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("PackagingProtocolId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ProtocolDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProtocolNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PackagingProtocolId");

                    b.ToTable("PersonnelAccessProtocols");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExecutorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FormSamplingFinishedProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Procedure")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckerId");

                    b.HasIndex("ExecutorId");

                    b.HasIndex("FormSamplingFinishedProductId");

                    b.ToTable("TabeProcedures");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableProductionPersonnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullNameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("PackagingProtocolId")
                        .HasColumnType("bigint");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FullNameId");

                    b.HasIndex("PackagingProtocolId");

                    b.ToTable("ProductionPersonnels");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableReceptionOfMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnalyticalSheetNumberOKK")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormReceptionAndMovementOfPackingMaterialId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFoilMeetsControlParameters")
                        .HasColumnType("bit");

                    b.Property<string>("ManufacturerSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceivedFoil")
                        .HasColumnType("int");

                    b.Property<int>("RemainingProduction")
                        .HasColumnType("int");

                    b.Property<string>("SAPPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftMasterId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FormReceptionAndMovementOfPackingMaterialId");

                    b.HasIndex("ShiftMasterId");

                    b.ToTable("ReceptionOfMaterials");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableSampleSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountOfSampleSelection")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeOKKId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FormSamplingFinishedProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeOKKId");

                    b.HasIndex("FormSamplingFinishedProductId");

                    b.ToTable("SampleSelections");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableSettingUpTechnologicalEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("FormSettingUpTechnologicalEquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceTechnicianId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FormSettingUpTechnologicalEquipmentId");

                    b.HasIndex("ServiceTechnicianId");

                    b.ToTable("SettingUpTechnologicalEquipments");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableVerificationAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("FormCheckingRejectionOfDefectiveTabletId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("TaskMasterId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FormCheckingRejectionOfDefectiveTabletId");

                    b.HasIndex("TaskMasterId");

                    b.ToTable("VerificationActions");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormAssignmentForMarkingThermalTransferLabelOnCorrugatedBox", b =>
                {
                    b.HasBaseType("NanolekPrototype.EntityModels.Models.PackagingProtocolForm");

                    b.Property<DateTime>("DateOfManufacture")
                        .HasColumnType("datetime2");

                    b.Property<int>("GTIN")
                        .HasColumnType("int");

                    b.Property<int>("InternalCode")
                        .HasColumnType("int");

                    b.Property<int>("PacksInCorrugatedBox")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<DateTime>("TaskGivenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskGivenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TaskGotDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskGotId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("TaskGivenId");

                    b.HasIndex("TaskGotId");

                    b.HasDiscriminator().HasValue("FormAssignmentForMarkingThermalTransferLabelOnCorrugatedBox");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormCheckingCheckweighingSetting", b =>
                {
                    b.HasBaseType("NanolekPrototype.EntityModels.Models.PackagingProtocolForm");

                    b.HasDiscriminator().HasValue("FormCheckingCheckweighingSetting");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormCheckingRejectionOfDefectiveTablet", b =>
                {
                    b.HasBaseType("NanolekPrototype.EntityModels.Models.PackagingProtocolForm");

                    b.Property<DateTime>("CheckingDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("FormCheckingRejectionOfDefectiveTablet");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormControlOfPrimaryPackaging", b =>
                {
                    b.HasBaseType("NanolekPrototype.EntityModels.Models.PackagingProtocolForm");

                    b.HasDiscriminator().HasValue("FormControlOfPrimaryPackaging");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormMaterialBalanceOfGPByLot", b =>
                {
                    b.HasBaseType("NanolekPrototype.EntityModels.Models.PackagingProtocolForm");

                    b.Property<DateTime>("CalcedByUserDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FormMaterialBalanceOfGPByLot_CalcedByUserDate");

                    b.Property<string>("CalcedByUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FormMaterialBalanceOfGPByLot_CalcedByUserId");

                    b.Property<DateTime>("CheckedByUserDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FormMaterialBalanceOfGPByLot_CheckedByUserDate");

                    b.Property<string>("CheckedByUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FormMaterialBalanceOfGPByLot_CheckedByUserId");

                    b.Property<DateTime>("CheckedPUByUserDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckedPUByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("FormMaterialBalanceOfGPByLot_Date");

                    b.Property<int>("ExitAccordingToTheRegulations")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishDateOfPacking")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("bit");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FormMaterialBalanceOfGPByLot_Observations");

                    b.Property<int>("PackagesCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftMasterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftMasterId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FormMaterialBalanceOfGPByLot_ShiftMasterId");

                    b.Property<DateTime>("StartDateOfPacking")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskMasterId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FormMaterialBalanceOfGPByLot_TaskMasterId");

                    b.HasIndex("CalcedByUserId");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("CheckedPUByUserId");

                    b.HasIndex("ShiftMasterId");

                    b.HasIndex("TaskMasterId");

                    b.HasDiscriminator().HasValue("FormMaterialBalanceOfGPByLot");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormReceptionAndMovementOfBulkProduct", b =>
                {
                    b.HasBaseType("NanolekPrototype.EntityModels.Models.PackagingProtocolForm");

                    b.Property<DateTime>("CalcedByUserDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FormReceptionAndMovementOfBulkProduct_CalcedByUserDate");

                    b.Property<string>("CalcedByUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FormReceptionAndMovementOfBulkProduct_CalcedByUserId");

                    b.Property<DateTime>("CheckedByUserDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FormReceptionAndMovementOfBulkProduct_CheckedByUserDate");

                    b.Property<string>("CheckedByUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FormReceptionAndMovementOfBulkProduct_CheckedByUserId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("FormReceptionAndMovementOfBulkProduct_Date");

                    b.Property<int>("DefectFirstPackageUnits")
                        .HasColumnType("int");

                    b.Property<int>("EntredIntoGPPackages")
                        .HasColumnType("int");

                    b.Property<int>("EntredIntoGPUnits")
                        .HasColumnType("int");

                    b.Property<int>("GarbageSecondPackageUnits")
                        .HasColumnType("int");

                    b.Property<int>("GarbageUnits")
                        .HasColumnType("int");

                    b.Property<int>("GetPRP")
                        .HasColumnType("int");

                    b.Property<int>("InternalCodeOfMaterial")
                        .HasColumnType("int")
                        .HasColumnName("FormReceptionAndMovementOfBulkProduct_InternalCodeOfMaterial");

                    b.Property<bool>("IsCorrespondToControlIndicators")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrespondToShelfLife")
                        .HasColumnType("bit");

                    b.Property<string>("PartSAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleSelectionUnits")
                        .HasColumnType("int");

                    b.Property<string>("ShiftMasterId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FormReceptionAndMovementOfBulkProduct_ShiftMasterId");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FormReceptionAndMovementOfBulkProduct_Specification");

                    b.HasIndex("CalcedByUserId");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("ShiftMasterId");

                    b.HasDiscriminator().HasValue("FormReceptionAndMovementOfBulkProduct");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormReceptionAndMovementOfPackingMaterial", b =>
                {
                    b.HasBaseType("NanolekPrototype.EntityModels.Models.PackagingProtocolForm");

                    b.Property<DateTime>("CalcedByUserDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CalcedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CheckedByUserDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("FormReceptionAndMovementOfPackingMaterial_Date");

                    b.Property<int>("ExpenseFor1000Packs")
                        .HasColumnType("int");

                    b.Property<int>("FormStatus")
                        .HasColumnType("int");

                    b.Property<int>("InternalCodeOfMaterial")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrespondenceEligibilityCriteria")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrespondsToConsumptionRate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSentToStorage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStoredInProduction")
                        .HasColumnType("bit");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FormReceptionAndMovementOfPackingMaterial_Observations");

                    b.Property<int>("Reconciliation")
                        .HasColumnType("int");

                    b.Property<int>("RemainingMaterial")
                        .HasColumnType("int");

                    b.Property<string>("ShiftMasterId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FormReceptionAndMovementOfPackingMaterial_ShiftMasterId");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpentOnBatch")
                        .HasColumnType("int");

                    b.HasIndex("CalcedByUserId");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("ShiftMasterId");

                    b.HasDiscriminator().HasValue("FormReceptionAndMovementOfPackingMaterial");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormSamplingFinishedProduct", b =>
                {
                    b.HasBaseType("NanolekPrototype.EntityModels.Models.PackagingProtocolForm");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationNUmber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtocolNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftMasterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaskMasterId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("ShiftMasterId");

                    b.HasIndex("TaskMasterId");

                    b.HasDiscriminator().HasValue("FormSamplingFinishedProduct");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormSettingUpTechnologicalEquipment", b =>
                {
                    b.HasBaseType("NanolekPrototype.EntityModels.Models.PackagingProtocolForm");

                    b.HasDiscriminator().HasValue("FormSettingUpTechnologicalEquipment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.PackagingProtocol", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "ResponsibleUserOOK")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserOOKId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "ResponsibleUserTLF")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserTLFId");

                    b.Navigation("ResponsibleUserOOK");

                    b.Navigation("ResponsibleUserTLF");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.PackagingProtocolForm", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.PackagingProtocol", "PackagingProtocol")
                        .WithMany("PackagingProtocolForms")
                        .HasForeignKey("PackagingProtocolId");

                    b.Navigation("PackagingProtocol");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableCheckingProcedure", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.FormCheckingCheckweighingSetting", "FormCheckingCheckweighingSetting")
                        .WithMany("CheckingProcedures")
                        .HasForeignKey("FormCheckingCheckweighingSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Executor");

                    b.Navigation("FormCheckingCheckweighingSetting");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableMovementOfBulkProduct", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.FormReceptionAndMovementOfBulkProduct", "FormReceptionAndMovementOfBulkProduct")
                        .WithMany("MovementOfBulkProducts")
                        .HasForeignKey("FormReceptionAndMovementOfBulkProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Executor");

                    b.Navigation("FormReceptionAndMovementOfBulkProduct");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TablePackagingControl", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.FormControlOfPrimaryPackaging", "FormControlOfPrimaryPackaging")
                        .WithMany("PackagingControls")
                        .HasForeignKey("FormControlOfPrimaryPackagingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "TaskMaster")
                        .WithMany()
                        .HasForeignKey("TaskMasterId");

                    b.Navigation("FormControlOfPrimaryPackaging");

                    b.Navigation("TaskMaster");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TablePersonnelAccessProtocol", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.PackagingProtocol", "PackagingProtocol")
                        .WithMany("PersonnelAccessProtocols")
                        .HasForeignKey("PackagingProtocolId");

                    b.Navigation("PackagingProtocol");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableProcedure", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "Checker")
                        .WithMany()
                        .HasForeignKey("CheckerId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.FormSamplingFinishedProduct", "FormSamplingFinishedProduct")
                        .WithMany("TableProcedures")
                        .HasForeignKey("FormSamplingFinishedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checker");

                    b.Navigation("Executor");

                    b.Navigation("FormSamplingFinishedProduct");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableProductionPersonnel", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "FullName")
                        .WithMany()
                        .HasForeignKey("FullNameId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.PackagingProtocol", "PackagingProtocol")
                        .WithMany("ProductionPersonnels")
                        .HasForeignKey("PackagingProtocolId");

                    b.Navigation("FullName");

                    b.Navigation("PackagingProtocol");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableReceptionOfMaterial", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.FormReceptionAndMovementOfPackingMaterial", "FormReceptionAndMovementOfPackingMaterial")
                        .WithMany("ReceptionOfMaterials")
                        .HasForeignKey("FormReceptionAndMovementOfPackingMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "ShiftMaster")
                        .WithMany()
                        .HasForeignKey("ShiftMasterId");

                    b.Navigation("FormReceptionAndMovementOfPackingMaterial");

                    b.Navigation("ShiftMaster");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableSampleSelection", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "EmployeeOKK")
                        .WithMany()
                        .HasForeignKey("EmployeeOKKId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.FormSamplingFinishedProduct", "FormSamplingFinishedProduct")
                        .WithMany("SampleSelections")
                        .HasForeignKey("FormSamplingFinishedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeOKK");

                    b.Navigation("FormSamplingFinishedProduct");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableSettingUpTechnologicalEquipment", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.FormSettingUpTechnologicalEquipment", "FormSettingUpTechnologicalEquipment")
                        .WithMany("SettingUpTechnologicalEquipments")
                        .HasForeignKey("FormSettingUpTechnologicalEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "ServiceTechnician")
                        .WithMany()
                        .HasForeignKey("ServiceTechnicianId");

                    b.Navigation("FormSettingUpTechnologicalEquipment");

                    b.Navigation("ServiceTechnician");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.TableVerificationAction", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.FormCheckingRejectionOfDefectiveTablet", "FormCheckingRejectionOfDefectiveTablet")
                        .WithMany("VerificationActions")
                        .HasForeignKey("FormCheckingRejectionOfDefectiveTabletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "TaskMaster")
                        .WithMany()
                        .HasForeignKey("TaskMasterId");

                    b.Navigation("FormCheckingRejectionOfDefectiveTablet");

                    b.Navigation("TaskMaster");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormAssignmentForMarkingThermalTransferLabelOnCorrugatedBox", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "TaskGiven")
                        .WithMany()
                        .HasForeignKey("TaskGivenId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "TaskGot")
                        .WithMany()
                        .HasForeignKey("TaskGotId");

                    b.Navigation("TaskGiven");

                    b.Navigation("TaskGot");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormMaterialBalanceOfGPByLot", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "CalcedByUser")
                        .WithMany()
                        .HasForeignKey("CalcedByUserId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "CheckedPUByUser")
                        .WithMany()
                        .HasForeignKey("CheckedPUByUserId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "ShiftMaster")
                        .WithMany()
                        .HasForeignKey("ShiftMasterId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "TaskMaster")
                        .WithMany()
                        .HasForeignKey("TaskMasterId");

                    b.Navigation("CalcedByUser");

                    b.Navigation("CheckedByUser");

                    b.Navigation("CheckedPUByUser");

                    b.Navigation("ShiftMaster");

                    b.Navigation("TaskMaster");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormReceptionAndMovementOfBulkProduct", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "CalcedByUser")
                        .WithMany()
                        .HasForeignKey("CalcedByUserId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "ShiftMaster")
                        .WithMany()
                        .HasForeignKey("ShiftMasterId");

                    b.Navigation("CalcedByUser");

                    b.Navigation("CheckedByUser");

                    b.Navigation("ShiftMaster");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormReceptionAndMovementOfPackingMaterial", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "CalcedByUser")
                        .WithMany()
                        .HasForeignKey("CalcedByUserId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "ShiftMaster")
                        .WithMany()
                        .HasForeignKey("ShiftMasterId");

                    b.Navigation("CalcedByUser");

                    b.Navigation("CheckedByUser");

                    b.Navigation("ShiftMaster");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormSamplingFinishedProduct", b =>
                {
                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "ShiftMaster")
                        .WithMany()
                        .HasForeignKey("ShiftMasterId");

                    b.HasOne("NanolekPrototype.EntityModels.Models.User", "TaskMaster")
                        .WithMany()
                        .HasForeignKey("TaskMasterId");

                    b.Navigation("ShiftMaster");

                    b.Navigation("TaskMaster");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.PackagingProtocol", b =>
                {
                    b.Navigation("PackagingProtocolForms");

                    b.Navigation("PersonnelAccessProtocols");

                    b.Navigation("ProductionPersonnels");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormCheckingCheckweighingSetting", b =>
                {
                    b.Navigation("CheckingProcedures");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormCheckingRejectionOfDefectiveTablet", b =>
                {
                    b.Navigation("VerificationActions");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormControlOfPrimaryPackaging", b =>
                {
                    b.Navigation("PackagingControls");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormReceptionAndMovementOfBulkProduct", b =>
                {
                    b.Navigation("MovementOfBulkProducts");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormReceptionAndMovementOfPackingMaterial", b =>
                {
                    b.Navigation("ReceptionOfMaterials");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormSamplingFinishedProduct", b =>
                {
                    b.Navigation("SampleSelections");

                    b.Navigation("TableProcedures");
                });

            modelBuilder.Entity("NanolekPrototype.EntityModels.Models.FormSettingUpTechnologicalEquipment", b =>
                {
                    b.Navigation("SettingUpTechnologicalEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
